# Generated by Django 5.1.7 on 2025-04-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogverse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
    ]
